openapi: "3.0.2"
info:
  title: UrlShortener API
  version: "1.0"
servers:
  - url: http://localhost:8080/
components:
  schemas:
    error:
      type: object
      properties:
        error:
          description: error message
          type: string
          required: true
paths:
  /make_vip_shorter:
    post:
      description: Creates short vip url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  description: url to make shorter
                  type: string
                  default: "https://github.com/DmitryVasilkovW/CV"
                vipKey:
                  description: short key to be mapped to long url
                  type: string
                  required: false
                timeToLive:
                  description: |
                    number of time-units this short url is going to be active. 
                    Maximum value must not be more than 48 hours
                  type: integer
                  required: false
                  default: 10
                timeToLiveUnit:
                  description: time unit for timeToLive parameter
                  type: string
                  enum:
                    - SECONDS
                    - MINUTES
                    - HOURS
                    - DAYS
                  required: false
                  default: HOURS
            example:
              longUrl: "https://github.com/DmitryVasilkovW/CV"
              vipKey: "exampleKey"
              timeToLive: 10
              timeToLiveUnit: "HOURS"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: invalid input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /make_shorter:
    post:
      description: Creates short url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                longUrl:
                  description: url to make shorter
                  type: string
                  default: "https://github.com/DmitryVasilkovW/CV"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  shortUrl:
                    type: string
                  secretKey:
                    type: string
        '400':
          description: invalid input parameters
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /admin/{secretKey}:
    get:
      summary: Get statistics for a redirection
      description: Returns statistics for the redirection associated with the given secret key.
      parameters:
        - name: secretKey
          in: path
          description: The secret key associated with the redirection.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the redirection statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  creationDate:
                    type: string
                    format: date-time
                    description: The creation date of the redirection.
                  usageCount:
                    type: integer
                    description: The number of times the redirection has been used.
        '404':
          description: Redirection not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
    delete:
      summary: Deletes a redirection by secret key
      description: Deletes a redirection associated with the given secret key.
      parameters:
        - name: secretKey
          in: path
          description: The secret key associated with the redirection to delete.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully deleted the redirection
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Redirection deleted successfully."
        '404':
          description: Redirection not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /{shortKey}:
    get:
      summary: Redirects to the long URL
      description: Resolves the short key to its corresponding long URL and redirects the client.
      parameters:
        - name: shortKey
          in: path
          description: The short key to resolve to a long URL.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Redirects to the resolved long URL
          headers:
            Location:
              description: The URL to which the client should be redirected.
              schema:
                type: string
        '404':
          description: Redirection not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
